name: Build & Push Dev Image

on:
  push:
    branches:
      - develop

jobs:
  build-dev:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Tag
        id: set-tag
        run: |
          REPO_NAME=${GITHUB_REPOSITORY,,}
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Build and Push Dev Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ env.REPO_NAME }}:dev

          build-args: |
            NEXT_PUBLIC_NHOST_SUBDOMAIN=${{ secrets.NEXT_PUBLIC_NHOST_SUBDOMAIN }}
            NEXT_PUBLIC_NHOST_REGION=${{ secrets.NEXT_PUBLIC_NHOST_REGION }}
            NEXT_PUBLIC_NHOST_AUTH_EMAIL=${{ secrets.NEXT_PUBLIC_NHOST_AUTH_EMAIL }}
            NEXT_PUBLIC_NHOST_AUTH_PASSWORD=${{ secrets.NEXT_PUBLIC_NHOST_AUTH_PASSWORD }}
            NEXT_PUBLIC_NHOST_GRAPHQL_URL=${{ secrets.NEXT_PUBLIC_NHOST_GRAPHQL_URL }}
